APP_NAME = "NOVA"
APP_PACKAGE = "com.nova.ai"
DEBUG = True
DEFAULT_WAKE_WORD = "NOVA"
DEFAULT_TTS_ENABLED = True
DEFAULT_SPEECH_RATE = 1.0
DEFAULT_PITCH = 1.0
DEFAULT_CONFIRMATION_MODE = True

# Core path configuration
DATA_DIR = "data"
